# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: UA-175973615-1
title: Ivy Jackson

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ivy Jackson

description: Senior Computer Science Student
author:
  name: Ivy Jackson
  email: ivyjshdx@gmail.com
  github: ivyjsgit
  linkedin: ivy-jackson-381585177
  bio: Senior Computer Science Major at Hendrix College, Intern at Disco Tray Studios

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
